image: docker:20
services:
  - docker:dind
stages:
  - prepare
  - build
  - deploy

prepare_base_img:
  stage: prepare
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "stag" || $CI_COMMIT_TAG
      changes:
        - "package.json"
        - "packages/*/package.json"
  variables:
    CURRENT_IMG_NAME: "${CI_REGISTRY_IMAGE}/frms-base"
    DOCKER_FILE_PATH: "./docker/Dockerfile.base"
  script:
    - chmod +x ./scripts/build-img.sh
    - ./scripts/build-img.sh
