image: docker:20
services:
  - docker:dind
stages:
  - prepare
  - build
  - deploy

variables:
  BASE_IMG_NAME: "frms-base"

.docker_authentication:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.get_environment:
  before_script:
    - chmod +x ./scripts/get-env.sh
    - source ./scripts/get-env.sh

prepare_base_img:
  stage: prepare
  extends: .docker_authentication .get_environment
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "stag" || $CI_COMMIT_TAG
      changes:
        - "package.json"
        - "packages/*/package.json"
  variables:
    IMG_NAME: "${CI_REGISTRY_IMAGE}/${BASE_IMG_NAME}"
    DOCKER_FILE_PATH: "./docker/Dockerfile.base"
  script:
    - chmod +x ./scripts/build-img.sh
    - ./scripts/build-img.sh
