image: docker:20
services:
  - docker:dind
stages:
  - prepare
  - build
  - deploy

variables:
  WEB_IMG_NAME: "frms-web"
  API_IMG_NAME: "frms-api"

before_script:
  - chmod +x ./scripts/get-env.sh
  - source ./scripts/get-env.sh

.docker_authentication:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build web:
  stage: build
  extends:
    - .docker_authentication
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "stag" || $CI_COMMIT_TAG
      changes:
        - "packages/web/**/*"
        - "packages/shared/**/*"
  variables:
    IMG_NAME: "${CI_REGISTRY_IMAGE}/${WEB_IMG_NAME}"
    DOCKER_FILE_PATH: "./docker/Dockerfile.web"
  script:
    - chmod +x ./scripts/build-img.sh
    - ./scripts/build-img.sh

build api:
  stage: build
  extends:
    - .docker_authentication
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "stag" || $CI_COMMIT_TAG
      changes:
        - "packages/api/**/*"
        - "packages/shared/**/*"
  variables:
    IMG_NAME: "${CI_REGISTRY_IMAGE}/${API_IMG_NAME}"
    DOCKER_FILE_PATH: "./docker/Dockerfile.api"
  script:
    - chmod +x ./scripts/build-img.sh
    - ./scripts/build-img.sh
