FROM node:16-alpine as build
WORKDIR /usr/src/frms
COPY package.json yarn.lock lerna.json tsconfig.json ./
COPY ./packages/shared ./packages/shared
COPY ./packages/web ./packages/web
RUN yarn install
RUN yarn workspace @frms/web run build

FROM node:16-alpine 
WORKDIR /usr/src/frms
COPY ./package.json  ./
COPY --from=build /usr/src/frms/packages/web/.next ./
RUN yarn install  --production --ignore-scripts --prefer-offline
CMD [ "yarn", "start" ]