FROM node:16-alpine as build
WORKDIR /usr/src/frms
COPY package.json yarn.lock lerna.json tsconfig.json ./
COPY ./packages/shared ./packages/shared
COPY ./packages/api ./packages/api
RUN yarn install
RUN yarn workspace @frms/api run build

FROM node:16-alpine 
WORKDIR /usr/src/frms
COPY ./package.json  ./
COPY --from=build /usr/src/frms/packages/api/dist ./
RUN yarn install  --production --ignore-scripts --prefer-offline
CMD [ "yarn", "start" ]